### ISSUE TITLE
Feedback/Suggestions/Framework

### ISSUE THREAD

**Issue by Martimoo0900** [daz3d/DazToBlender#11]
Version 2.1.0
In this version only Expressions is being imported into Blender.
I tried selecting the new Presets but they doesn't import:
Face Controls
Expressions
Visemes
All Body Morphs

Only bones is showing up and not the visual rig. Maybe this is on purpose and Rigify is the way to go now?

I'm working on a Tutorial that is utilizing this Addon and it's not that this addon should be catered to my needs. But i do feel that the goal of this addon should be to Export a fully rigged character with all the correct morphs, and every feature on top of that is a nice to have, like animation, posing etc.

Exporting from Daz3D, is not very intuitive when it comes to deciding Morphs. Even with minimal morphs ticked, it will export all expressions that I have installed.

Possible solution:

Having a section for each type of morphs like:
Joint Corrective Morphs(JCM) (Select one)
Flexions (Select one)
Expressions (Select multiple)
Visemes (Select multiple)
and for genesis 8.1
FACS (Select one)
FACS Units (Select one)
All standard morphs are selected by default.

Quick example mockup - maybe having the same export window for every bridge would make sense?
Maybe include subdivision in this window?
![Daz3D export](https://user-images.githubusercontent.com/20815751/106644356-4bb5d780-658b-11eb-9fe6-43d9822ecf78.jpg)
This would make it a lot more clear what is being exported.

When exporting from Daz to other DCC, morph detail is lost and this makes the teeth's, morphs look really bad as it's being exported in subdivision 0 in most cases.
For Blender i usually export in SubD 1 to keep some of the details, but this slows me down when it comes to animation/posing.

Possible solution: 
could be to implemented Daz3D Subdivision Algorithm "Catmark" into other DCC, i tried searching about this "Catmark" algorithm but i didn't find much about. But it seems to be based on Open Subdiv which most DCC supports.

Or it would have to be specific for each DCC, in Blenders case maybe Multires could help?

**Comment by schroef** [comment]
```
For Blender i usually export in SubD 1 to keep some of the details, but this slows me down when it comes to animation/posing.
```
Did you try to use simplify in this case. Using this should make the animating and posing much faster. This wont help on high poly mesh object of course. Perhaps using a lower poly cage would work. Ive seen solution artists use in this case. The make a prop which will be swapped with the hi-res in rendertime. They use a custom prop to toggle it and it simply connected to the viewport and render icon in the outliner

**Comment by schroef** [comment]
PS in this release i do read they have made improvement and deleting none used morphs
https://github.com/daz3d/DazToBlender/releases/tag/1.9.9

**Comment by samjay3d** [comment]
https://github.com/daz3d/DazToBlender/releases/tag/2.1.0

Looks like we didn't add the release this is the current public release. 

Also Thanks! Martimoo0900 we are currently looking into the reworking morphs in the export thanks for sharing :)

**Comment by schroef** [comment]
PS you can also check this PDF of the original creator, it shows more in depth what each setting does. I dont understand why this info isnt shown made available easier though. Some of the info is a bit harder to understand, mainly due to the original dev not being English. But it is very detailed!

http://docs.daz3d.com/lib/exe/fetch.php/public/read_me/index/70891/daztoblender_user_s_manual.pdf

**Comment by samjay3d** [comment]
Thanks for the share! Yeah I have worked with Mitchy before on this and he did an amazing job. There are two of us working on the codebase now. We are trying our best to keep each feature existing as we update and fix up current issues.

**Comment by schroef** [comment]
@samjay3d yeah this addon is amazing work, the amount and level work that has been done is simply insane!

I shared the link for @Martimoo0900 he asked a feature, if i understand his post correct, which basically already exists. Yet the there is hardly any info about this addon. Thats why i linked the PDF

**Comment by samjay3d** [comment]
@Martimoo0900  There is a new morph dialog currently working on more documentation but, its very similar to the unreal and unity process.  This is a more of a stepping stone we will be doing a larger redesign in the future. 
https://www.daz3d.com/forums/discussion/482401/daz-to-blender-new-bridge-update-ready-for-testing#latest
