### ISSUE TITLE
Bend Control etc. do not work after Importing but Old DTB and butaixianran's revised DTB work

### ISSUE THREAD

**Issue by windreaver0118** [daz3d/DazToBlender#126]
With Bent Control （Zev0）included in Morphs List，after importing, JCMs work but no effect when tweaking any Bend Control slides. However old DTB and butaixianran‘s revised DTB work fine~ Pls take a look~

**Comment by danielbui78** [comment]
I think it may be related to a function that is not yet implemented in C++: can you please check if in the bottom-left corner of Morph Selection Dialog of either the old DTB/butaixianran version and uncheck the "Disable Links" option.  Please let me know if unchecking this disables the Bend Control slider from working.  Thanks!

**Comment by windreaver0118** [comment]
> I think it may be related to a function that is not yet implemented in C++: can you please check if in the bottom-left corner of Morph Selection Dialog of either the old DTB/butaixianran version and uncheck the "Disable Links" option. Please let me know if unchecking this disables the Bend Control slider from working. Thanks!

I tried several takes, if I uncheck Disable Links, the bridge did not export any morphs into blender. I found nothing in the Morph List after importing.  It seemed also strange and I could not find any related document for this option....

**Comment by danielbui78** [comment]
@windreaver0118 Please test the pre-release build here:
https://github.com/daz3d/DazToBlender/releases/tag/2022.1.pre.12.35

Let me know if it fixes your problems related to Bend Control not working.  If there are things still not working, please let me know exactly what they are.  Thanks very much.

**Comment by windreaver0118** [comment]
> @windreaver0118 Please test the pre-release build here: https://github.com/daz3d/DazToBlender/releases/tag/2022.1.pre.12.35
> 
> Let me know if it fixes your problems related to Bend Control not working. If there are things still not working, please let me know exactly what they are. Thanks very much.

Daniel, I found this version works well for Bend Control, so far so good~ Appreciated!!

BTW, there's another issue... I applied a pose on a G8 base female and exported Skeletal Mesh. After importing in Blender, the Pose is not correct. I found there're XYZ rotation values on hip, abdomen lower/upper nodes, etc. in DAZ but zero values in blender.
Then I exported Animation with only 1 frame, the Pose in blender is correct. The pose I used is in Genesis 8 Starter Essentials, named Base Pose Sitting B.  Pls take a look if possible. Thanks in advance!

**Comment by windreaver0118** [comment]
> There are some known issues regarding Import Pose functionality. Please open a new issue if it's still a problem for you.
> 
> Glad to hear that Bend Control is finally working. If there are no more Bend Control issues, I will close this issue. Thanks.

Yeah，you may close Bend Control issue~~ I will furthere test the Posing function then open a new issue as needed~ Thanks~
