### ISSUE TITLE
How is that 2.79 version coming

### ISSUE THREAD

**Issue by schroef** [daz3d/DazToBlender#16]
I was wondering how your 2.79 version is coming. Ive already made mine, but that was done with older version of this script.

**Comment by Popinjayishuman** [comment]
We currently have no plans to support 2.79.

**Comment by schroef** [comment]
Yeah i can understand, i doubt many people are still using bl 2.79
I used it because i used an external render engine which i helped upgrade and support a bit for Bl 2.79
