### ISSUE TITLE
exporting morph from daz to blender

### ISSUE THREAD

**Issue by kachupika** [daz3d/DazToBlender#160]
I have tried exporting a nail/ear morph from blender to daz. Using vertex edit or sculpting causes same issue. Daz states morph geometry doesn't match. I have reinstalled and updated bridge plugin via the updated release. Thank you.

**Comment by danielbui78** [comment]
The most common reasons for geometry to not match is that you exported the original mesh incorrectly to blender or that you did not preserve vertex order when importing, modifying and exporting the mesh inside Blender.  Please Note: The "To Daz Morph" button is designed to work with shapekeys for a figure's body and may not work in all situations.  Exporting directly to OBJ is recommended in those situations.

- Make sure you have Subdivision Level set to 0 and Resolution Level set to Base in the Mesh Resolution settings of the Paramaters Tab in Daz Studio.
- Make sure you import, modify, export with-out changing the vertex order in Blender
- Export an OBJ with only the single modified mesh, (use Scale 100, Y up, -Z forward)

**Comment by kachupika** [comment]
I did not have the sudivision set to 0, but i just retried it with everything set how you stated. I still have the same issue. I can work with the body scale being off, I can always just rescale in Daz. But it doesn't stop the geomtery not matching when i work on the nail morph. Am i not allowed to extrude the vertexes? is that considered modifying the vertex order?

**Comment by danielbui78** [comment]
If by "extrusion", you mean you are creating entirely new vertices at the point of extrusion, then YES you are modifying the number of vertices and thus also modifying the vertex order.  Here is how to create a nail morph without modifying vertex order:

https://youtu.be/E0I8mZIykCw

**Comment by kachupika** [comment]
Thank you! I was doing too much it seems (when I grabbed to extend and not extrude). Hopefully this works for the ear morph. I also realized from your import back to daz, that I had a setting wrong, so my size scale is no longer an issue.

**Comment by danielbui78** [comment]
I will close this issue since there have been no other problems or questions.

Best Regards
