### ISSUE TITLE
JCM - CBS import

### ISSUE THREAD

**Issue by HI4AN** [daz3d/DazToBlender#165]
I would like to know how soon you will be able to add support for importing Jcm morphs to correctly display the flexion of joints for genesis 9. For version 9, they are now called CBS

**Comment by danielbui78** [comment]
Auto JCM / CBS should already be working with Genesis 9, make sure you click to "Allow Execution" of the automatic python driver scripts.  If you are still having issues, please include video or screenshots and detailed steps of how to reproduce your problem.  Also include all Daz assets that you are using and links to the Daz store for them if possible.

**Comment by danielbui78** [comment]
If you are referring to the Morph Selection to support Genesis 9 via the Add JCM buttons in the Daz to Blender dialog window of Daz Studio, that is planned to be updated within the next few weeks.

**Comment by HI4AN** [comment]
> Если вы имеете в виду обновление окна выбора морфинга для поддержки Genesis 9 с помощью кнопок Добавления JCM в диалоговом окне Daz в Blender в Daz Studio, планируется обновление в течение следующих нескольких недель.

Yes, that's right, that's what I meant. Thank you for your hard work I will be waiting
