### ISSUE TITLE
bridge not showing in blender addons

### ISSUE THREAD

**Issue by trebor8** [daz3d/DazToBlender#167]
Hi
On a new laptop (windows 11) installed latest versions of Daz, Blender 3.5 and the bridge. The bridge installs into Daz Ok, but not in blender addons.
I've checked everywhere all the files/folders. Re-installed the bridge through daz central. Still not happening.

Please, can anyone help?

**Comment by danielbui78** [comment]
@trebor8 
Did you follow the steps to install the Blender plugin?  Make sure you watch and follow the steps at time 1:13: https://youtu.be/eXjfekMV4sE?t=73

Written instructions for installing the Blender plugin are also available on the main github page: https://github.com/daz3d/DazToBlender#3-how-to-install

Please let us know if you're still having difficulty after following these steps.  Please include screenshots or videos of what is happening.

**Comment by trebor8** [comment]
Hi

Trust me I've done all these things and more, I ve given up totally, it isn't worth the stress

Regards
________________________________

**Comment by danielbui78** [comment]
I am closing this issue since you appear final in your decision to not accept further help.  Please feel free to open a new issue in the future if things change for you.

Best Regards
