### ISSUE TITLE
Import with plugin 2022.2.19.43 and Blender 3.5 fails

### ISSUE THREAD

**Issue by jtorres19749** [daz3d/DazToBlender#168]
I update the plugin to ver 2022.2.19.43 and Blender to 3.5. Then I export from Dazz 4.21.05 an Genesis 8 Male.   All right to this point , I think. 

![image](https://user-images.githubusercontent.com/40840567/236773078-2fe05420-f07f-4324-91cc-8b1a38f9cfca.png)

![image](https://user-images.githubusercontent.com/40840567/236773285-7f57fe0a-4147-42fb-9db6-baff2c1ae1e2.png)

But in Blender do not show the Character on list, and fails when I select Import New Genesiss Figure.

![image](https://user-images.githubusercontent.com/40840567/236773722-b18f3994-7cd1-4825-badf-34e142e2d5bd.png)

Could you help me with this?  Do you need more info?  What can I do?

**Comment by danielbui78** [comment]
Enable the `Cycles Render Engine` add-on.  Then restart Blender and try the import again.  I will modify a future release so that it will work with Cycles disabled.

**Comment by jtorres19749** [comment]
Excellent! That works fine. Thank you.
