### ISSUE TITLE
Transparency maps mapped from Alpha chanel

### ISSUE THREAD

**Issue by odhinnsrunes** [daz3d/DazToBlender#17]
Transparency maps imported to Blender are using the alpha channel instead of the Colour channel of the Texture Map node. All transparency textures I've ever seen in DAZ use black for transparent and white for opaque, not the alpha channel, so I have to go through all textures with transparencies on import and move the link from the alpha of the texture node to the color. This is very time-consuming, especially on things like hair objects which often have several channels.

**Comment by samjay3d** [comment]
Thanks for letting us know! I will fix that issue. Currently, I am going through and redesigning our Materials to work more similar to how it looks in Daz Studio and have been noticing many issues like you mentioned. In the meantime, we have changed how the materials are created. Within the bridge, there is a blend file with all the Node Groups that if you edit them in the scene any updates would be added to your import.

https://github.com/daz3d/DazToBlender/tree/gen8_1-import-fixes

**Comment by odhinnsrunes** [comment]
Thanks!  I'll take a look.

**Comment by samjay3d** [comment]
It should be fine now. We are still getting a weird bug that eyelashes aren't working correctly in cycles only but, let me know if you see it working better.
