### ISSUE TITLE
Shape keys are not driven by bones

### ISSUE THREAD

**Issue by charleshetier** [daz3d/DazToBlender#19]
> Blender versions tried: 2.91.2, 2.92
Daz studio 4.15
Daz to Blender 2.1.0 (updated today)

With the basic genesis 8 female (I have also tried 8.1), the character seems to be imported properly but when posing it, the shape keys are not following.
As a result, the mesh is deformed only by bones and joints are that strange:
![image](https://user-images.githubusercontent.com/8912998/109621948-dd3d4880-7b3b-11eb-8f3d-8c4d3cfabf9e.png)

I really love the way importing a character into blender is easy with this bridge. Tell me if I can do anything to help!

**Comment by chlbrn** [comment]
I am not sure I understand you correctly, shape keys are vertex position or offset, they just add some value to corresponding vertices location. They don't follow bone movement IMO.

**Comment by charleshetier** [comment]
Sorry for my bad explanation and/or my average English :-)
I remember a version of the addon where the shape key values of the mesh had a driver bound to bones rotation. For example, when the knee is bent, the armature is bending the leg based on the vertex group values (this is what is shown on the screen capture). But the deformation is not very natural and is mixed with corrective shape keys.

At import, the mesh is properly tied to the armature, and I can also see all the corrective shape keys on the mesh, but they are not synchronized. The last time I used the addon, they were synchronized with a driver.

Am I missing something?
Again, sorry if my explanation is not clear.... :-(

**Comment by andy-m-github** [comment]
Hi, I think this is the same issue I reported - #14. I've come up with a set of fixes to one of the bridge files, so that shapekeys will be correctly applied as the figure is posed. You could try:

1. backup the database.py file.
2. replace the 2 tables.
3. try to re-import your figure in blender.

Details are in my issue report. I don't know if this will fix what you see, but it would be great if it does.

**Comment by charleshetier** [comment]
Thanks @andy-m-github for your awesome answer and investigation.
Unfortunately, it didn't solved anything on my side. The thing is: There is absolutely no driver on any of the shape key of my exported model. Moreover on another attempt I encountered this:
![image](https://user-images.githubusercontent.com/8912998/110294970-d5285180-7ff0-11eb-863f-e25a643a1066.png)
The skeleton is not properly scaled + all shape keys exported without any driver tied to them.
As if the process have halted before the end, but the console ends with a success message.

**Comment by samjay3d** [comment]
We currently know about both of these issues. And are working on fixing them. We will keep you posted when we got a fix for it.

**Comment by andy-m-github** [comment]
That's a shame. I haven't seen a case where there are no drivers at all, but saying that, I am testing against the g8f base figure only. Below is a snapshot showing the drivers section for the shin bones on g8f - roughly the same pose as in your first screenshot.

![DTB Drivers Shin](https://user-images.githubusercontent.com/79371110/110391883-04c27280-8060-11eb-8d83-d0ea4d0f82a7.jpg)

**Comment by samjay3d** [comment]
There's been a huge update for shape keys it still needs a lot of work but, take a look and let us know what you think :) 
https://www.daz3d.com/forums/discussion/482401/daz-to-blender-new-bridge-update-ready-for-testing#latest
