### ISSUE TITLE
Enhancement request: Morph transfer dialog

### ISSUE THREAD

**Issue by Seraphiel0** [daz3d/DazToBlender#26]
Clarity: The export script appears to transfer the current shape regardless of morphs chosen in this dialog, so when this appears it's not immediately clear that it's possible to skip it without picking anything and have the character exported as-is.

Workflow:  An option on the previous dialog like "Export no morphs/Export current or active morphs only/Use last selection/Load preset/Display morph transfer dialog" would be helpful for those times where I just want to export a scene as quickly as possible without fidgeting with the morph selection.

**Comment by samjay3d** [comment]
Thanks for the request. Yeah I agree something is necessary. Currently though if you press cancel with the dialog is open it will skip all morphs. Think of this morph dialog as phase 1 :)

**Comment by samjay3d** [comment]
An option has been added in the develop branch will now allow you to skip the dialog :) 
![image](https://user-images.githubusercontent.com/71744685/112941925-302b0100-90e4-11eb-8f39-c50da95c53c9.png)
