### ISSUE TITLE
JCMs not exported

### ISSUE THREAD

**Issue by TarouMaso** [daz3d/DazToBlender#33]
Hello,

I use the latest version 2.3.1 but the JCMs are not exported.
![image](https://user-images.githubusercontent.com/8605767/114306209-79fbea00-9adb-11eb-8bc0-6bb1e0b8ca3e.png)
This is how it should look like:
![image](https://user-images.githubusercontent.com/8605767/114306223-8ed87d80-9adb-11eb-8c29-6642dc90f2ef.png)

It also applies expression morphs on the stockings for example:
![image](https://user-images.githubusercontent.com/8605767/114306311-db23bd80-9adb-11eb-854d-605da70fa06e.png)

**Comment by samjay3d** [comment]
The morphs are getting applied to all the meshes currently we are looking at a fix for this in the near future. Could I see your export choices in Daz. Did you choose the JCMs at export?

**Comment by TarouMaso** [comment]
I added the model specific ones:
![image](https://user-images.githubusercontent.com/8605767/114506945-c3ab1880-9c32-11eb-9cac-63131bc75ab0.png)

**Comment by samjay3d** [comment]
I will verify tomorrow as well. I would need to check those specific ones but, usually (from the characters I tested) the jcms that specific to characters are applied on top of the base jcms. So you should export those as well to get the way it is looking in Daz Studio. 
How it works in Daz (Usually) all the JCMs in your scene are being applied to the Genesis 8 Figure and based on which FBM you have applied it uses that info. So, for example, if you have Tara 8 at 40% and Sahira 8 and 60% on top of the base JCMs it is applying the jcm of Sahira 8 at 60% of the value it should be and 40% for Tara 8.

**Comment by TarouMaso** [comment]
Yeah adding all works, but it also adds tons that aren't used and just take away memory. And surprisingly many doubles that all activate at the same time even though nothing distorts. 
![image](https://user-images.githubusercontent.com/8605767/114510930-8dbc6300-9c37-11eb-8fdc-5fd0e259603b.png)
