### ISSUE TITLE
Figures in Group cause silent failure

### ISSUE THREAD

**Issue by Seraphiel0** [daz3d/DazToBlender#35]
First, thanks for adding the checkbox to skip the morph dialog.  This speeds things up a lot for me.

Error repro:
1) Load figure.
2) Parent figure under a Group node (I do this regularly to manage scenes with lots of figures so I can hide them and all their attachments easily)
3) Run DTB export.

Result:
1) Initial dialog (Figure/Env/Both) doesn't appear at all.
2) The script appears to run with all the usual behaviors (items being made visible, figure pose being reverted to zero) but the export file doesn't appear in the export folder; running the Blender plugin doesn't find the exported data.

Workaround:
Manually unparent figure from Group node before running DTB export.

**Comment by samjay3d** [comment]
Ah ok, I get what you mean. I can create a workaround fast that can fix that but, temporarily the only way the process can continue if your export is the next group.

I will share an example in a bit. Thanks for the catch.

**Comment by samjay3d** [comment]
https://github.com/daz3d/DazToBlender/tree/develop

wanna give this a test? I had to redo the export choice logic but, it should work with groups now. It may still have bugs gonna finalize it tomorrow.

**Comment by Seraphiel0** [comment]
In my (very hasty and rudimentary) testing this does appear to resolve this particular issue by automatically unparenting the figure from the group.  Thanks!
