### ISSUE TITLE
Issues with bones and rig when importing into blender

### ISSUE THREAD

**Issue by beepbooped** [daz3d/DazToBlender#37]
![gfs](https://user-images.githubusercontent.com/82426993/114488282-1824a880-9bdf-11eb-85a4-561cabbc0f6d.png)

I've updated, I've reinstalled Daz Studio, I've manually installed the addon in blender but the rig and it's bones always import wrong. I don't know why. I don't see anyone else complaining about this issue so I'm guessing it's something I've done but I don't know what

**Comment by beepbooped** [comment]
okay so i noticed that when i open daz and try to load in a gen8 body, it says i'm missing a file and that it was the gen3 file so i downloaded the gen3 starter bundle. the rig is mostly okay now but the head rig is still the same
![ok](https://user-images.githubusercontent.com/82426993/114490126-4788e480-9be2-11eb-8df6-a0a73e5f473c.PNG)

**Comment by beepbooped** [comment]
Okay, once again testing things out. But I realized that the issue with the first pic only arises when I use the 'legs length' morph, is there a way to fix this so I can keep the morph without getting the rig issue

**Comment by samjay3d** [comment]
Want to give it a shot?
Before it was only calculating for that offset you were seeing for Full Body Morphs now it should be working for the morphs you said you used just tested it myself. 

Just a note though just make you don't choose these morphs to export as the skeleton will be to the size in Daz,  but the mesh will export without the morphs applied. 

https://github.com/daz3d/DazToBlender/tree/develop
![image](https://user-images.githubusercontent.com/71744685/114499263-929ef980-9bda-11eb-827f-f55c5be1c592.png)

**Comment by beepbooped** [comment]
Works like a charm! Thank you!!!

**Comment by samjay3d** [comment]
Awesome glad it worked and thanks for sharing!
