### ISSUE TITLE
bridge only import first frame of animation 

### ISSUE THREAD

**Issue by swogks** [daz3d/DazToBlender#38]
and every other keyframes have same pose with first frame. 
so importing animation is not importing animation, it just does only import first pose of animation during animation period.
I'm using Blender 2.92 and Daz Studio 4.15 Pro.

first frame of importing g8 female - bow-g8f
![2](https://user-images.githubusercontent.com/13850079/114642112-481e9980-9d0e-11eb-85c6-5afdab9e6ec2.PNG)

50th frame of same model
![3](https://user-images.githubusercontent.com/13850079/114642120-4a80f380-9d0e-11eb-8116-c277fb8871fe.PNG)

**Comment by samjay3d** [comment]
Hi there so it seems that animation is the aniMate2 block you need to right-click the bar and bake it into key frame animation.
![image](https://user-images.githubusercontent.com/71744685/114663088-9bf99600-9cae-11eb-870e-0450c6f8600b.png)

**Comment by swogks** [comment]
@samjay3d It works! Thank you so much!
