### ISSUE TITLE
Install Bridge Fails...

### ISSUE THREAD

**Issue by Rcott** [daz3d/DazToBlender#39]
Spent all day with the new update 2.31...Install from Daz Central..and Installs in Blender 2.9...But you can't activate it as Blender doesn't know it has been installed. No sign of a zip file anywhere...
Made up a new zip from the DBT folder Central installed in Blender 2.9 and was able to activate it...first try to import Daz Character ended in this error...
![image](https://user-images.githubusercontent.com/40922389/115125116-53c6c600-9f83-11eb-95c4-5baa6527facb.png)

**Comment by samjay3d** [comment]
Sorry for that. If you are looking for a quick workaround this error has been fixed in the develop branch and will be added in the next few weeks as a release.

**Comment by samjay3d** [comment]
https://github.com/daz3d/DazToBlender/tree/develop
