### ISSUE TITLE
Shapekey breaks Blender rendering

### ISSUE THREAD

**Issue by chilli2** [daz3d/DazToBlender#46]
I imported a genesis 8 model from DAZ to Blender and some of the shapekeys end up corrupted somehow. 

- The shapekeys work as intended in viewport solid mode
- Viewport rendered mode (Cycles or Eevee) work without the shapekeys set
- Setting the shapekeys and setting the viewport in rendered mode freezes Blender to a halt

The reason that makes the think the shapekeys end up corrupted somehow is that if I create a new shapekey [from mix], then the new shapekey works as intended.

I reported this bug to Blender as well
https://developer.blender.org/T87971

**Comment by samjay3d** [comment]
Which shapekeys were you export I can take a look if its happening from the daz side instead.

**Comment by chilli2** [comment]
There's only one shapekey on the model (in the blender file posted in the link). I made the file simple to test with and deleted other shapekeys, but the same problem happened for some of the other shapekeys as well (including some of the basic daz bodymorphs)

**Comment by samjay3d** [comment]
It seems to not be an error with the shapekeys but, as they said on the blender side but, the eyebrows. Oddly tho when I tried using the eyebrows you have added in your blend scene in a new import they appear as intended. Did you do any updates the geometry after export? If I delete the eyebrows tho in your current scene it renders fine. 

If you share the export files found ( C:\Users\Your username\Documents\DAZ 3D\Bridges\Daz To Blender\Exports\FIG ) 
I can take a closer look if all you did was delete shape keys.

**Comment by chilli2** [comment]
I did a re-import and it worked. The error also didn't repeat itself in a while, so the issue can be closed
