### ISSUE TITLE
couple of issues

### ISSUE THREAD

**Issue by Dunravin** [daz3d/DazToBlender#51]
1. the download does not create a zip file, in the appdata/roaming/blender foundation folder, the daz addon musty be zipped up manually to install in blender
2. the export from daz creates a FIG_0 folder in exports folder which causes the blender import to crash, user has to copy the files from FIG_0 and paste into the FIG root folder.
3. once all the above is done blender import wont crash with errors but.... it does absolutely nothing other than create some collections, no geometry, nothing imported

complete fail

**Comment by samjay3d** [comment]
1. Zip file is not necessary if you have an issue installing please let us know more details. When the folder is installed in your version of blender it just needs to be enabled in Blender.
2. This is incorrect. the FIG folder holds all the exports out of Daz that are characters, so if you want to import multiple characters. if you add it to the root folder it won't import correctly. 
3. Same as above you shouldn't be getting import at all if u moved the folder. 

Please share more info of what you are seeing or please open a ticket for more direct support.
