### ISSUE TITLE
Armature, Shapekeys, and Pose

### ISSUE THREAD

**Issue by katekittaly** [daz3d/DazToBlender#52]
Genesis 8 female--a more complex pose, but it's not supposed to look horrific like this. DAZ 4.15, Bridge 2.3.1.1

A. All shapekeys are missing
B. Mesh and armature are not the same size, resulting in armature not matching up to mesh, or sometimes it will be the right size but lower.
C. Pose warps mesh in strange ways because of armature
D. Clicking on shin IK takes armature into edit mode but does not show IK bones for posing (at least not that I can find). Okay, edit, I found them behind the feet, but they don't work.
E. Porting clothes over on an empty armature (no genesis figure attached but still poseable clothes) twists bones in strange ways so that mesh is warped. This used to work fine on the old bridge.

Blender Version:
![Screenshot 1](https://user-images.githubusercontent.com/84484382/119073541-85d0ab00-b9bb-11eb-8b0d-a6b1acbcdcf4.png)
![Screenshot 2](https://user-images.githubusercontent.com/84484382/119073551-89643200-b9bb-11eb-905a-cdfcaf900653.png)

This is what she's supposed to look like in DAZ (added a dress in this screenshot, so ignore).
![Screenshot 3](https://user-images.githubusercontent.com/84484382/119073714-c9c3b000-b9bb-11eb-9058-48da2e88a1ec.png)

**Comment by Popinjayishuman** [comment]
Hey there Katekittaly, we would love to look into this further but first we need a little more information about the asset(s) and pose(s) you were using when the issue occurred.

**Comment by katekittaly** [comment]
She's a Gen 8 based character with SASE Erica and a ton of morphs to change
her appearance. No clothes or scenery, since I handle all that in Blender.
Ruyun hair for gen 8. I can't remember which pose I started with.
Newer versions of the bridge aren't doing it this badly anymore, but
there's still the misalignment problem you asked about in my  next report.
I'll answer it there. Thanks for getting back to this!
