### ISSUE TITLE
Daz to Blender Bridge not working on new Pc 

### ISSUE THREAD

**Issue by sawja2** [daz3d/DazToBlender#53]
On my old Pc it was no Problem evrything worked. On my new Pc i do evrything like on my old Pc. But if i try to import something, blender give me this error. :(

<a href="https://ibb.co/7CG6QH4"><img src="https://i.ibb.co/XLzvD98/error-bridge.jpg" alt="error-bridge" border="0"></a>

**Comment by Popinjayishuman** [comment]
This error has been solved in the newest release, please update and let us know if you have any other problems!
