### ISSUE TITLE
Import error message must be valid and informative

### ISSUE THREAD

**Issue by powerbroker** [daz3d/DazToBlender#54]
The import script reports "Appropriate FBX is not exists!"

1. "... DOES not exist_" is grammatically correct.

2. The exact missing file must be reported instead of general wording like "Appropriate FBX", e.g. "B_FIG.fbx in C:\KDV\Documents\DTB\FIG\FIG1 is missing". 
In case the FBX must fit some criteria, the criteria must be reflected in the error message, e.g. "C:\KDV\Documents\DTB\FIG\FIG1\B_FIG.fbx 'ApplicationVendor' value must be 'DAZ 3D' instead of 'SuppaDuppaPlaceholder'"

Reported this way the errors are much easier to locate and fix, without the need to debug the script sources.

**Comment by Popinjayishuman** [comment]
Thanks for the input, I'll pass it on to the developers!
