### ISSUE TITLE
Error on import in Blender

### ISSUE THREAD

**Issue by strezoiualex** [daz3d/DazToBlender#55]
![image](https://user-images.githubusercontent.com/39642858/119714366-b05ab200-be5a-11eb-921d-ec2a5926b907.png)

**Comment by strezoiualex** [comment]
V 2.3.5- beta
Blender 2.9.1

**Comment by samjay3d** [comment]
Did you replace the blender and daz side?

**Comment by strezoiualex** [comment]
YES.
![image](https://user-images.githubusercontent.com/39642858/119756549-98efe900-be9b-11eb-88a1-d9643ef644e3.png)

![image](https://user-images.githubusercontent.com/39642858/119756603-a86f3200-be9b-11eb-93da-cf55849f0374.png)

**Comment by samjay3d** [comment]
Sorry, missed this. Could you try to update and rerun this again. We have made a  bunch of changes since then and most likely it has solved this issue.
