### ISSUE TITLE
Rig mismatch with G8F figure

### ISSUE THREAD

**Issue by exverxes** [daz3d/DazToBlender#57]
I have noticed that if figure uses a morph that has a translation in it and fixes it by adding opposite translation applied to the hip (Daz Studio -> "Height" parameter for example), then whole rig does not match the figure. It is translated precisely by that translation on the hip. 

Reproduction:
Create G8F in Daz studio
Change Height using Shapes (Actor->Full Body->Real World->Height).
Export to Blender
Import in blender
Observe whole rig translated.

Check Y translation on G8F hip
Observe that translation in blender matches that translation value in daz studio.

**Comment by Popinjayishuman** [comment]
We have tested to confirm and this issue has been resolved in the newest release, please update.
