### ISSUE TITLE
2.3.6-beta exporting morphs not working due to absolute path

### ISSUE THREAD

**Issue by rathren** [daz3d/DazToBlender#58]
![image](https://user-images.githubusercontent.com/10924228/120561551-07d1c280-c405-11eb-8435-6102b3d24d18.png)
(I don't even have a "D:/" drive)
I know It is just a pre-release but I wanted to tell, you in case this is not known :)

**Comment by samjay3d** [comment]
Thanks you for pointing this out it has been fixed for the current release!
