### ISSUE TITLE
Error after updating to v2.3.6

### ISSUE THREAD

**Issue by JakeLeyser** [daz3d/DazToBlender#59]
Hello,

I downloaded the DazToBlender bridge after a long time, the new version seems to be v2.3.6.

When I export the model from Daz using the script, it seems to work fine but when I try to import it into Blender with the plugin I get this error (pastebin link below) and the bones seems to be lumped together on the head for some reason, could you please check and tell me what I am doing wrong here? I didnt have this problem when I used to use v2.3.1

Thank you.

![image](https://user-images.githubusercontent.com/62128111/120575632-13da7600-c43f-11eb-9214-2cc271935da1.png)

https://pastebin.com/3Cawih9X

**Comment by enversl** [comment]
same problem(

**Comment by ericdelappe** [comment]
Seems to be an issue with Blender 2.93. I tested the addon in 2.92 and it works fine.

Devs, please update the addon to be compatible with the latest version of Blender.

**Comment by samjay3d** [comment]
We are taking a look at this now will let you know when this is resolved!

**Comment by samjay3d** [comment]
If you try out the newest version in Develop it should work now. Running some more tests then I will package a prerelease for GitHub.

**Comment by samjay3d** [comment]
https://github.com/daz3d/DazToBlender/archive/refs/heads/develop.zip

**Comment by JakeLeyser** [comment]
Do I have to replace the Daz Plugin as well or is it enough to just replace Blender Plugin?
