### ISSUE TITLE
how to disable automatically checking depth feature in blender navigation preference

### ISSUE THREAD

**Issue by hamzawsg** [daz3d/DazToBlender#62]
when i import a model it automatically check the depth box... i don't want uncheck it every time i import a model
![Capture](https://user-images.githubusercontent.com/54221035/120797327-2d151c80-c53c-11eb-86c2-b751ca3d53ac.PNG)

**Comment by samjay3d** [comment]
https://github.com/daz3d/DazToBlender/releases/tag/2.3.9-beta

You can now disable that in the Import Settings.
