### ISSUE TITLE
Animations aren't coming through

### ISSUE THREAD

**Issue by kenjibailly** [daz3d/DazToBlender#67]
So when I export my figure with my animations to Blender using the Daz3D to Blender Bridge, it creates all the keyframes but nothing happens.
Seems like all the keyframes are just set for a location, but they're all the same location.

I'm not sure what I can do anymore, I tried a bunch of different animations but it's the same for all.
I tried different genesis figures, but couldn't get any working.
I'm running Blender 2.93 and Daz Studio 4.15 Pro and DazToBlender 2.3.7

What is coming through though?
The textures, the poses, props, pretty much everything else.

**Comment by Popinjayishuman** [comment]
Hey there Kenjibailly. https://github.com/daz3d/DazToBlender/issues/38 This is a similar issue we've had before. Check to see if these steps help, if not let us know!
