### ISSUE TITLE
Armatures are still not aligning to mesh

### ISSUE THREAD

**Issue by katekittaly** [daz3d/DazToBlender#69]
It's better than previous versions, but still causes some issues. This is a Gen 8 figure.

Shapekeys are also still missing. 

![Capture](https://user-images.githubusercontent.com/84484382/122153667-706f6500-ce31-11eb-9019-9216793d72df.PNG)

**Comment by Popinjayishuman** [comment]
Which figure are you using here?

**Comment by katekittaly** [comment]
> 
> 
> Which figure are you using here?

Gen 8 female. The armature jumps up in edit mode, and it causes problems when parenting clothes to the armature in Blender, making the mesh jump. I figured out that you can fix it in Pose Mode, Clear Transforms, Reset Unkeyed.

If there is another figure already in the Blender file, the new figure won't import posed but in rest pose. Also, am I doing something wrong? All my figures before 8.1 came out imported with shapekeys to control expressions, and now there are never shapekeys.

**Comment by Popinjayishuman** [comment]
You have to select the correct morphs for either 8 or 8.1 in the 'choose morphs' section when exporting from daz. You will be able to the adjust using the sliders in the daz to blender sidebar. After testing, I was able to import a new figure into blender fine and it retained it's pose, are you still having this issue? If possible could you link the duf file so we can test under the same circumstances?

**Comment by katekittaly** [comment]
I do apologize, but I was unable to recreate this now as well. I'll try to keep a better record of things when reporting now that I understand more about what you need.

Thanks so much for your help!
