### ISSUE TITLE
Follow Blender bone naming convention

### ISSUE THREAD

**Issue by yhlai-code** [daz3d/DazToBlender#72]
Blender's bones have their [naming convention](https://docs.blender.org/manual/en/latest/animation/armatures/bones/editing/naming.html):

> First you should give your bones meaningful base-names, like “leg”, “arm”, “finger”, “back”, “foot”, etc.
> 
> If you have a bone that has a copy on the other side (a pair), like an arm, give it one of the following separators:
> 
> Left/right separators can be either the second position “L_calfbone” or last-but-one “calfbone.R”.
> 
> If there is a lower or upper case “L”, “R”, “left” or “right”, Blender handles the counterpart correctly. See below for a list of valid separators. Pick one and stick to it as close as possible when rigging; it will pay off.
> 
> Examples of valid separators:
> 
> (nothing): handLeft –> handRight
> 
> “_” (underscore): hand_L –> hand_R
> 
> “.” (dot): hand.l –> hand.r
> 
> “-” (dash): hand-l –> hand-r
> 
> ” ” (space): hand LEFT –> hand RIGHT
> 
> Note
> 
> Note that all examples above are also valid with the left/right part placed before the name. You can only use the short “L”/ “R” code if you use a separator (e.g. “handL”/ “handR” will not work!).
> 
> Before Blender handles an armature for mirroring or flipping, it first removes the number extension, e.g. “.001”.
> 
> You can copy a bone named “bla.L” and flip it over using Flip Names. Blender will name the copy “bla.L.001” and flipping the name will give you “bla.R”.

Please consider making the imported bones follow this.

**Comment by Popinjayishuman** [comment]
Thanks for the input! I will pass on your suggestion to the dev team.

**Comment by elizaveta-markova** [comment]
This script will rename the bones following the Blender convention:

https://blenderartists.org/t/script-simple-daz-to-blender-renaming-vertex-groups-bones-script/1268519

See #128 , however.
