### ISSUE TITLE
Daz to Blender Bridge only works once per file?

### ISSUE THREAD

**Issue by Artofmind99** [daz3d/DazToBlender#74]
Hey, I've run into a problem where I can only export my model to Blender one time. The first time I use the bridge, it works great. If I want to try it again in the same session, I get an error card(object) in Blender. Even if I close them both out and re-open Daz with the file I was using, I can't get it to export through the bridge. I have tried deleting the export files in the Documents/DAZ 3D/Bridges/Daz To Blender/Exports/FIG location but it does nothing to fix it. Any help would be much appreciated! Thanks

**Comment by Popinjayishuman** [comment]
hey Artofmind99, we'd like to look into this further, can you let us know which asset(s) you were using when the issue occurred?
