### ISSUE TITLE
Texture folder gets erased during each Daz to Bridge push.

### ISSUE THREAD

**Issue by NateGriffin** [daz3d/DazToBlender#76]
It seems that the folder that contains textures for models (should be -' ~\Documents\DAZ 3D\Bridges\Daz To Blender\Exports\FIG\FIG0\Textures\...')  is erased each time you use the Bridge, so it will only contain the files for the most recent push and any others will come up as missing when opening old blend files. Is there currently any workaround for this?

**Comment by samjay3d** [comment]
The best method for keeping your textures if you don't want to use the locations in daz studio is to write the images to the scene.

https://docs.blender.org/manual/en/latest/files/blend/packed_data.html

You can pack the data into the blend file and then unpack the file and write the textures. 

The collect textures is a small addition which isn't that great until we add custom imports and being able to choose export path.

**Comment by NateGriffin** [comment]
Thanks for the quick response. Will do.
