### ISSUE TITLE
Daz Horse 2

### ISSUE THREAD

**Issue by damenmofa** [daz3d/DazToBlender#78]
Daz Horse 2 doesn't come in at all. It shows a small sign instead saying that the vertex order has changed and some other things that do not seem to be realted to the horsie at all.

**Comment by Popinjayishuman** [comment]
Hi there, damenmofa, thanks for the post! We were aware of the issue and it has been solved in the latest update of the Daz to Blender bridge. We used to only be able to export genesis characters with a skeleton but we have expanded the possibilities! Please update and let us know if you still have issues.

**Comment by damenmofa** [comment]
Hey,
Thank you for the response.
The horse now does import but not correctly. I have attached a screenshot. The pose seems to be roughly correct but the hair and the ears are not.
