### ISSUE TITLE
Imported Morph scales the whole figure 

### ISSUE THREAD

**Issue by Micmacmoe** [daz3d/DazToBlender#79]
Good Day

Daz 4.15.02
DtB version 2.3.9
Blender 2.93.1
Auto run phyton script enabled

When i import a Morph like proposed from  
Nazzareno Giannelli>> https://www.youtube.com/watch?v=TEXzmUSzX30

the morph will just **scale the whole figure** instead of morphing a part of the geometry.

 Is this a probably problem of units?? 
The exported obj file frome blender looks fine, importing the file via >> Object >> Morph loader pro  also works without any issues. But using the slider just scales the figure in whole.

best regards
mic

**Comment by Popinjayishuman** [comment]
Hey there, can you explain in more detail which morph you were trying to import and the process?
