### ISSUE TITLE
Only Armature imports - Shows Python error

### ISSUE THREAD

**Issue by ineverwin** [daz3d/DazToBlender#86]
I'm unable to import any figure from Daz to Blender. I get the error attached below (it's several errors).

Only the armature loads: no shape or textures (though the list of clothing does appear in the scene objects, but none are visible in any way). I tried importing the generated FBX and received the same error. 

Importing a prop (with no morphs) works fine. All characters fail, with or without clothing, posing, etc.

I have the most up-to-date version of DazToBlender installed (2.4, manually installed from GitHub), Blender  2.92, and Daz 4.15 (all on Windows 10).
![blendererror](https://user-images.githubusercontent.com/61524097/128864958-95d7a479-cac1-45e5-88f6-739d610a134e.jpg)

**Comment by Popinjayishuman** [comment]
Hi there, Could you please share your FBX file with us so we could take a look on our end?
