### ISSUE TITLE
Eyelashes and Eyebrows doen't follow the face expressions

### ISSUE THREAD

**Issue by JC-Sutter** [daz3d/DazToBlender#9]
It seems everythink works except the eyelashes and the eyebrows don't follow the face expressions. Its seems to be a bug, other people have the same issue.

**Comment by samjay3d** [comment]
Should be working now 
https://www.daz3d.com/forums/discussion/482401/daz-to-blender-new-bridge-update-ready-for-testing#latest
Give it a shot.
